# Generated by Django 5.1 on 2024-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fooditems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('foodtype', models.CharField(max_length=15)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
    ]
