# Generated by Django 5.1 on 2024-09-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_checkout_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
